services:
  # Redis for storing posted article IDs (deduplication)
  redis:
    image: redis:7-alpine
    container_name: fdc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # n8n workflow automation
  n8n:
    image: n8nio/n8n:latest
    container_name: fdc-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ChangeMeToSecurePassword123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Manila
      # Allow n8n to connect to Redis
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
    volumes:
      - n8n-data:/home/node/.n8n
      - ./workflows:/home/node/workflows
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    name: fdc-news-network